version: '3'
services:
  sundash:
    build: .
    container_name: sundash
    command: npm run dev:docker
    environment:
      - NODE_ENV=development
      - CONFIG_FOLDER=/app/storage
      - DOCKER_PROXY_NETWORK=web
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app
